version: "3"

services:
  app:
    image: docker-nextjs
    build: ./
    networks:
      - nginx
    environment:
      - VIRTUAL_HOST=ceboostup.kmitl.cloud
      - VIRTUAL_PORT=3000
networks:
  nginx:
    name: nginx_network
    driver: bridge